package:
   name: intake
   version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  entry_points:
    - intake-server = intake.cli.server.__main__:main
    - intake = intake.cli.client.__main__:main
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - jinja2
  run:
    - python
    - numpy
    - pandas
    - msgpack-python
    - msgpack-numpy
    - requests
    - tornado
    - jinja2
    - ruamel_yaml >=0.15.0
    - dask
    - python-snappy
    - appdirs
    - xarray

test:
  requires:
    - pytest
    - pytest-cov
    - coverage
  commands:
    - intake list -h
    - intake-server -h
    - py.test --cov=intake --pyargs intake

about:
  home: https://github.com/ContinuumIO/intake
  license: BSD
  license_file: LICENSE
  summary: Data ingest catalog system
